config/routes.rb
TestApp::Application.routes.draw do
  root to: 'static_pages#home'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"

  match '/help' => 'static_pages#help', via: :get
  match '/new_user' => 'users#new', via: [:get, :post]
  match '/user_index' => 'users#index', via: :get
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save :create_remember_token

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.haml
!!!
!!!
%html
  %head
    %title= yield(:title)
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %div.navbar-inner
        %div.container
          = link_to "Test app", root_path, id: "logo"
          %nav
            %ul.nav.pull-right
              %li= link_to t(".home"), root_path
              %li= link_to t(".help"), help_path
              - if signed_in?
                %li= link_to t(".users"), user_index_path
                %li.dropdown#fat-menu
                  %a{href: "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown"}
                    Account
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to "#{h current_user.name}'s #{h t(".profile")}", current_user
                    %li= link_to t(".settings"), '#'
                    %li.divider
                    %li= link_to t(".signout"), logout_path, :method => :delete
              - else
                %li= link_to t(".signin"), login_path
                %li= link_to t(".newuser"), new_user_path
    - if flash[:alert]
      %div.alert
        %p#notice
          = flash[:alert]
    %div.center.hero-unit
      %div.container
        =yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Test App", '/', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/' %></li>
              <li><%= link_to "Help",    help_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", user_index_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "#{current_user.name}'s Profile", current_user %></li>
                    <li><%= link_to "Settings", '#' %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", logout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", login_path %></li>
                <li><%= link_to "New User", new_user_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <% if flash[:alert] %>
      <div class="alert">
        <p id="notice"><%= flash[:alert] %></p>
      </div>
    <% end %>
    <div class="center hero-unit">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/help.haml
%h1= t("static_pages.about_header")
%h2= t("static_pages.about_body")
%p= link_to t("static_pages.signup"), new_user_path, :class => "btn btn-large btn-primary"

app/views/static_pages/help.html.erb
<h1>About Test App</h1>

<h2>
  This Application was created with Ruby on Rails 4.0.0
</h2>

<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>

app/views/static_pages/home.haml
%h1= t("static_pages.hello")
%h2= t("static_pages.hello_body")
%p= link_to t("static_pages.signup"), new_user_path, :class => "btn btn-large btn-primary"

app/views/static_pages/home.html.erb
<h1>Welcome to the Test App</h1>

<h2>
  This is the home page for the test application.
</h2>

<%= link_to "Sign up now!", 'new_user', class: "btn btn-large btn-primary" %>

app/views/users/_form.haml
= form_for(@user) do |f|
  -if @user.errors.any?
    %div.alert
      %h2= "#{pluralize(@user.errors.count, "error")} #{t(".error_message")}"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %div.field
    = f.label :name, t(".name")
    = f.text_field :name
  %div.field
    = f.label :password, t(".password")
    = f.password_field :password
  %div
    = f.label :password_confirmation, t(".confirmation")
    = f.password_field :password
  = f.submit t(".submit"), :class => "btn btn-large btn-primary"

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= f.submit 'New User', class: "btn btn-large btn-primary" %>
  
<% end %>

app/views/users/edit.haml
%h1 Editing users
= render 'form'
= link_to t('.profile'), @user
= link_to t(".all"), users_path 

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.haml
%h1 Listing users
%table
  %thread
    %tr
      %th Name
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to t(".show"), user
%br

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.haml
%h1 New user
= render 'form'

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>
</div>

app/views/users/show.haml
%p
  %strong Name:
  = @user.name
= link_to t(".edit"), edit_user_path(@user)
|
= link_to t(".index"), users_path

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>